# Site settings
baseURL = "https://traze.iteratec.de/"
languageCode = "en-us"
title = "traze"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[[menu.top]]
    name = "Spectate"
    weight = 10
    url = "watch/"

# Site parameters
[params]

    # Meta
    description = "Traze is a multi client online tronlike game with MQTT protocol. It aims to provide a playground for various game clients, AI game bots, and showcase of a resonable secure MQTT application, and it’s fun! You can write your own game client and participate in the game using the protocol documented on this page."
    author = "devs @iteratec"
    keywords = "Tron, MQTT, IOT, ..."
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "traze"
    headerDescription = ""
    
    # Back-to-top button name
    bttButton = ""
