# Site settings
baseURL = "https://traze.iteratec.de/docs"
languageCode = "en-us"
title = "TRAZE documentation"
theme = "hugo-simpledoc-theme"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

# Top menu
[[menu.top]]
    name = "TRAZE Game Web UI"
    weight = 10
    url = "https://traze.iteratec.de"
[[menu.top]]
    name = "Another useful link, like docs for MQTT?"
    weight = 20
    url = "http://mqtt.org/"

# Site parameters
[params]

    # Meta
    description = "TRAZE docs - documentation to develop clients for the game TRAZE"
    author = "devs @iteratec"
    keywords = "Tron, MQTT, IOT, ..."
    
    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "TRAZE docs"
    headerDescription = ""
    
    # Back-to-top button name
    bttButton = ""