name: github pages
# see https://github.com/peaceiris/actions-hugo#getting-started

on:
  push:
    branches:
      - '**' # matches every branch

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.54.0' # same like hugo in debian Dockerfile
          extended: true

      - name: Build
        run: hugo --baseURL https://iteratec.github.io/traze-docs/
        working-directory: src

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # deploy generated content only for master branch
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
